In [49]:
import pandas as pd

In [50]:
train = pd.read_csv('data/down_train.csv')
valid = pd.read_csv('data/down_valid.csv')
test = pd.read_csv('data/down_test.csv')
VOZ = pd.read_csv('data/down_VOZ.csv')

In [51]:
train

                                                   text  label
0     Biển không thể lên thăm cầu vồng, còn cầu vồng...      0
1                            Tin vui nhất trong ngày!!!      0
2                          Không đẹp nhưng nhiu options      0
3     Cá nhân tôi càng thấy các cô muôn phần đẹp hơn...      0
4                    Sevilla thắng loạt đá luân lưu 5-4      0
...                                                 ...    ...
1513  Có vẻ đẹp nhưng hơi...nhăn nhở .Bình thường có...      1
1514  Đọc mà không kìm nổi sự giận dữ trước hành vi ...      1
1515  Anti toàn lôi cái kq 8-2 ra nói nhưng mà kiểu ...      1
1516               Ác quá ác ! Cho tù khổ sai cho nhớ !      1
1517            2 kẻ này phải xử lý mạnh. Thật căm phẫn      1

[1518 rows x 2 columns]

In [52]:
valid

                                                  text  label
0    Có phải xe bồn cố tình đánh lái sang làn xe má...      0
1    Quê nghèo lên xứ Bình DươngSao không chí thú t...      0
2    Tại sao bạn trai cháy đc ko báo công an ngay đ...      0
3    Luật pháp không xử lý hình sự thật nặng những ...      0
4           Hàng cấm đó nha mấy bạn sắp bị tuyệt chủng      0
..                                                 ...    ...
459                     Tập thể dục mà quên tập ý thức      1
460   Biden có thể nhầm lẫn chứ không bao giờ nói dối.      1
461                          Bản án nhẹ tựa lông hồng.      1
462  Có lẽ ai muốn hiểu rõ về phim cần google trước...      1
463                         Hết cái để nổ rồi Trump ơi      1

[464 rows x 2 columns]

In [53]:
test

                                                  text  label
0                   Người ăn không hết kẻ lần chẳng ra      1
1      Nhiều người cứ nghĩ đạp xe là văn minh. haizzzz      1
2                                          Rất văn hoá      0
3    Đời ta ba mươi đời nó. Mua chiếc xe cũng chỉ p...      0
4    Tước bằng lái vĩnh viễn đi. Chạy lếu láo thật,...      1
..                                                 ...    ...
995  biệt thự nhà riêng to đùng thế kia mà chủ (hay...      1
996  Trong cái khó ló cái khôn, người tài thật sự k...      0
997  Bánh trung thu sao lại phải có quả trứng muối ...      0
998  Cấp 1 nói chung và lớp 1 nói riêng theo tôi có...      0
999                               Tôi thấy hay đó chứ.      0

[1000 rows x 2 columns]

In [54]:
VOZ

                                                     text  label
0       bọn trẻ trâu manh động lắm, may cho fen ko bị ...      1
1       Thế cho tao hỏi bọn 92 ở mẽo hoặc các nước khá...      1
2                                                    đbrr      1
3       bọn trẻ trâu manh động lắm, may cho fen ko bị ...      1
4       Thử phản đi, hè thằng Mp3 nó tống 2 thằng đấy ...      0
...                                                   ...    ...
113061  Điểm yếu lớn nhất của hắn, có lẽ là sự cố chấp...      0
113062                                       Việt Hấp Hối      0
113063  Thì ra thằng này đầu tuần lên lập thớt xàm nìn...      0
113064                                Có cái đb đc 15 củ.      1
113065                                       có cl :lmao:      1

[113066 rows x 2 columns]

In [55]:
from sklearn.model_selection import train_test_split

train_VOZ, valid_VOZ = train_test_split(VOZ, test_size=0.2, random_state=42)

In [56]:
train = pd.concat([train, train_VOZ])
valid = pd.concat([valid, valid_VOZ])
train

                                                     text  label
0       Biển không thể lên thăm cầu vồng, còn cầu vồng...      0
1                              Tin vui nhất trong ngày!!!      0
2                            Không đẹp nhưng nhiu options      0
3       Cá nhân tôi càng thấy các cô muôn phần đẹp hơn...      0
4                      Sevilla thắng loạt đá luân lưu 5-4      0
...                                                   ...    ...
76820                                           Thầy cc à      1
110268  Lên cơn là niệm rồi . Cái virus oái oăm thật, ...      0
103694  đẹp đấy thím, mình cũng đang có ý dắt gái đi ă...      0
860     Nhà ông bị thằng nào nó trộm nước thì có, 3 ng...      1
15795   cứ tinh thần lấy vin nô làm gốc thì đ' bao giờ...      0

[91970 rows x 2 columns]

In [57]:
train.sample(frac=1, random_state=42).reset_index(drop=True)

                                                    text  label
0      Kệ cmm, kể cả thằng Bình qua đây mà đ báo trướ...      1
1      Vịt là trg hợp đặc biệt, cả thế giới chỉ có Vị...      0
2      cần ủng hộ.. Các cao thủ võ lâm cũng chỉ đến t...      1
3                                  Post cái ảnh k ra hồn      0
4      bộ emblem rotto trc mình đang làm bên comicvn ...      0
...                                                  ...    ...
91965  Với vận tốc em nghĩ là thấp nhất của bọn con t...      1
91966  Cảm ơn thím vì đã rep rất lịch sự, nhưng có vẻ...      0
91967  Rảnh được 1 tí định viết về con bạn thân của v...      0
91968  Con tôi cũng đang học chương trình cải cách gi...      1
91969  Có cái cc ấy mà xe gió nhanh hơn gió. Ma sát l...      1

[91970 rows x 2 columns]

In [58]:
valid.sample(frac=1, random_state=42).reset_index(drop=True)

                                                    text  label
0                                               Dâm tiện      1
1      tôi ghét ông Erik vc, nhìn cứ ưỡn ẹo tđn ấy. Q...      0
2      7 né và con pet của nó, aka ngu nô, chém thằng...      0
3      Rô đĩ đúng là luôn biết cách để media chú ý về...      0
4      1 mẹ ny thì bằng con mẹ nó 100 đơn vị thông th...      1
...                                                  ...    ...
23073  Bận quá fen. Với mình nhận ra ngồi nhớ về nhữn...      0
23074  Với vận tốc em nghĩ là thấp nhất của bọn con t...      1
23075  Cần éo gì chạy ? Dư nợ đâu chả đụng nóc Có dn ...      1
23076  Chả cần nhà nước. Làm cty/tập đoàn lớn đây, cá...      1
23077  bọn trẻ trâu manh động lắm, may cho fen ko bị ...      1

[23078 rows x 2 columns]

In [59]:
train.to_csv('data/train.csv', index=False)
valid.to_csv('data/valid.csv', index=False)